site_name: USER DOCUMENTATION
dev_addr: 127.0.0.1:2000
theme: material
#markdown_extensions:
#  - toc:
#    baselevel: 2
#theme: readthedocs
#plugins:
#    - search
#    - pdf-export
nav:
 - Introduction: 'intro.md'
 - â–¶ï¸ Quick start guide: 'quick_start_guide.md'
 - Sensors: 'sensors.md'
 - Data upload: 'data_upload.md'
 - MyBroodminder: 'mybroodminder.md'
 - Mellisphera: 'mellisphera.md'
 - Data interpretation: 'data_interpretation.md'
 - Beecounted: 'beecounted.md'
 - ğŸ‰ New T2 Swarminder: 'new_t2sm.md'
 - _: 'void.md'
 - FAQ: 'faq.md'
 - Support: 'support.md'