site_name: USER DOCUMENTATION
dev_addr: 127.0.0.1:2000
theme: material
site_url: https://doc.mellisphera.com
site_description : precision beekeeping documentation system Broodminder-Mellisphera
plugins:
  - search:
      lang: 'en'
  - pdf-export
extra_css:
    - css/extra.css
nav:
 - index.md
 - Introduction: 'intro.md'
 - ‚ñ∂Ô∏è Quick start guide: 'quick_start_guide.md'
 - Sensors: 'sensors.md'
 - Data upload: 'data_upload.md'
 - MyBroodminder: 'mybroodminder.md'
 - Mellisphera: 'mellisphera.md'
 - Data interpretation: 'data_interpretation.md'
 - Beecounted: 'beecounted.md'
 - üéâ New T2 Swarminder: 'new_t2sm.md'
 - _____: 'void.md'
 - FAQ: 'faq.md'
 - Support: 'support.md'
 - _____: 'void.md'
 - Hub Troublehooting : 'troubleshooting_cell_hub.md'
