site_name: GUIDE UTILISATEUR
dev_addr: 127.0.0.1:2000
theme: material
site_url: https://doc.mellisphera.com
site_description : precision beekeeping documentation system Broodminder-Mellisphera
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
plugins:
  - search:
      lang: 'fr'
  - pdf-export
extra_css:
    - css/extra.css
nav:
 - index.md
 - Introduction: 'intro.md'
 - ‚ñ∂Ô∏è Guide de d√©marrage rapide: 'quick_start_guide.md'
 - Capteurs: 'capteurs.md'
 - R√©cup√©ration de donn√©es: 'data_upload.md'
 - MyBroodminder: 'mybroodminder.md'
 - Mellisphera: 'mellisphera.md'
 - Interpretation: 'data_interpretation.md'
 - Science collaborative: 'beecounted.md'
 - üéâ T2 Swarminder: 'new_t2sm.md'
 - _____: 'void.md'
 - FAQ: 'faq.md'
 - Support: 'support.md'
 - _____: 'void.md'
 - D√©panner le Hub GSM : 'troubleshooting_cell_hub.md'
 - Maintenance d'hiver : 'winter_service.md'
      

# check for documentation on commands
# https://squidfunk.github.io/mkdocs-material/reference/lists/


#google_analytics: ['UA-125989472-3', 'mkdocs.org']
#markdown_extensions:
#  - toc:
#    baselevel: 2
#theme: readthedocs
#nav:
#plugins:
#    - search
#    - pdf-export