site_name: GUIDE UTILISATEUR
dev_addr: 127.0.0.1:2000
theme: 
  name : material
  features:
    - navigation.indexes
  palette:
    scheme: default
site_url: https://doc.mellisphera.com
site_description : Guide Utilisateur BroodMinder
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
plugins:
  - search:
      lang: 'fr'
#  - pdf-export    # disable this item to run tests on the doc (mkdoc serve without building pdf every time
extra_css:
  - css/extra.css
nav:
  - index.md
  - Introduction: 'intro.md'
  - Guide de d√©marrage rapide üöÄ : 'quick_start_guide.md'
  - Capteurs: 
    - Gamme de capteurs : 'capteurs_gamme.md'
    - Spec technique: 'capteurs_tech_specs.md'
    - Installation: 'capteurs_install.md'
    - W3 en kit: 'W3_section/W3-Assembly-Guide.md'
    - Balance DIY: 
      - Guide utilisateur: DIY_section/guide_utilisateur_diy.md
      - Mod√®le CRI: DIY_section/model_cri.md
  - R√©cup√©ration de donn√©es: 
    - App Bees: 'beesApp.md'
    - Hub 4G/WiFi: 'hub.md'
    - SubHub: 'subhub.md'
  - Analyse de donn√©es:
    - MyBroodminder: 'mybroodminder.md'
    - Mellisphera: 'mellisphera.md'
    - Interpretation: 'data_interpretation.md'
    - P√©rim√®tre fonctionel: 'features.md'

  - Science collaborative: 'beecounted.md'
  - _____: 'void.md'
  #- Balance DIY üÜï :
  #  #- DIY_section/index.md
  #  - Guide utilisateur: DIY_section/guide_utilisateur_diy.md
  #  - Mod√®le CRI: DIY_section/model_cri.md
  #- T2 Swarminder: 'new_t2sm.md'
  #- _____: 'void.md'
  - FAQ: 'faq.md'
  - Support: 'support.md'
  - D√©panner l'ancien Hub 4G : 'troubleshooting_cell_hub.md'
  - Maintenance d'hiver : 'winter_service.md'
  - _____: 'void.md'


# check for documentation on commands
# https://squidfunk.github.io/mkdocs-material/reference/lists/


#google_analytics: ['UA-125989472-3', 'mkdocs.org']
#markdown_extensions:
#  - toc:
#    baselevel: 2
#theme: readthedocs
#nav:
#plugins:
#    - search
#    - pdf-export